language: python

python:
  - "2.7"
install:
  - pip install -r requirements.txt
before_script:
  - sudo mkdir /webDriver
  - sudo wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
  - tar -xf geckodriver-v0.19.1-linux64.tar.gz
  - sudo mv gecko* /webDriver
  - export PATH=$PATH/:/webDriver
script:
  - pytest
